import { execFile } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { APP, appHome } from '../config.js';
import type { SchedulerStatus } from './index.js';

const TASK = `${APP}-sync`;
// Names used by earlier versions; removed on install/uninstall.
const OLD_TASKS = [`${APP}-sync-interval`, `${APP}-sync-logon`];

function schtasks(args: string[]): Promise<{ code: number; out: string }> {
  return new Promise((resolve) => {
    execFile('schtasks.exe', args, { windowsHide: true }, (err, stdout, stderr) => {
      resolve({ code: err ? 1 : 0, out: String(stdout) + String(stderr) });
    });
  });
}

const wscript = () => path.join(process.env.SystemRoot || 'C:\\Windows', 'System32', 'wscript.exe');
const vbsPath = () => path.join(appHome(), 'sync-hidden.vbs');
const startupShim = () =>
  path.join(process.env.APPDATA || '', 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup', `${APP}-sync.vbs`);

/** The built cli.js next to this file's parent folder, resolved to an absolute path. */
function cliPath(): string {
  return path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'cli.js');
}

/**
 * A tiny VBScript that runs `node cli.js sync --quiet` with a hidden window
 * (window style 0). Absolute paths so the task works without the user's PATH.
 */
function writeVbs(): string {
  const q = (s: string) => `""${s}""`;
  const cmd = `${q(process.execPath)} ${q(cliPath())} sync --quiet`;
  const vbs = [
    `' Generated by ${APP}. Runs a background sync without flashing a console window.`,
    'Set sh = CreateObject("WScript.Shell")',
    `sh.Run "${cmd}", 0, False`,
    '',
  ].join('\r\n');
  fs.mkdirSync(appHome(), { recursive: true });
  fs.writeFileSync(vbsPath(), vbs, 'utf8');
  return vbsPath();
}

const xmlEscape = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/**
 * Task definition XML. Unlike plain `schtasks /SC MINUTE`, this lets the task
 * run on battery, catch up after sleep, and never pile up instances.
 */
function taskXml(intervalMinutes: number, vbs: string, withLogon: boolean): string {
  const user = xmlEscape(`${process.env.USERDOMAIN || os.hostname()}\\${os.userInfo().username}`);
  const start = new Date(Date.now() + 60_000).toISOString().slice(0, 19);
  const logon = withLogon ? `\n    <LogonTrigger>\n      <Enabled>true</Enabled>\n      <UserId>${user}</UserId>\n    </LogonTrigger>` : '';
  return `<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>${APP}: sync Claude Code sessions in the background</Description>
  </RegistrationInfo>
  <Triggers>
    <TimeTrigger>
      <Repetition>
        <Interval>PT${intervalMinutes}M</Interval>
        <StopAtDurationEnd>false</StopAtDurationEnd>
      </Repetition>
      <StartBoundary>${start}</StartBoundary>
      <Enabled>true</Enabled>
    </TimeTrigger>${logon}
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>${user}</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <ExecutionTimeLimit>PT10M</ExecutionTimeLimit>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>${xmlEscape(wscript())}</Command>
      <Arguments>//B //Nologo "${xmlEscape(vbs)}"</Arguments>
    </Exec>
  </Actions>
</Task>
`;
}

async function createFromXml(xml: string): Promise<{ code: number; out: string }> {
  const file = path.join(appHome(), 'task.xml');
  // schtasks expects UTF-16 LE with a BOM for XML input.
  fs.writeFileSync(file, '\ufeff' + xml, 'utf16le');
  try {
    return await schtasks(['/Create', '/F', '/TN', TASK, '/XML', file]);
  } finally {
    fs.rmSync(file, { force: true });
  }
}

export async function install(intervalMinutes: number): Promise<void> {
  const vbs = writeVbs();
  for (const t of OLD_TASKS) await schtasks(['/Delete', '/F', '/TN', t]);

  // Preferred: one task with interval + logon triggers.
  if ((await createFromXml(taskXml(intervalMinutes, vbs, true))).code === 0) {
    fs.rmSync(startupShim(), { force: true });
    return;
  }
  // Some machines refuse logon triggers without admin: interval task + Startup folder shim.
  let r = await createFromXml(taskXml(intervalMinutes, vbs, false));
  if (r.code !== 0) {
    // Last resort: plain schtasks (does not run on battery by default).
    const tr = `"${wscript()}" //B //Nologo "${vbs}"`;
    r = await schtasks(['/Create', '/F', '/SC', 'MINUTE', '/MO', String(intervalMinutes), '/TN', TASK, '/TR', tr]);
    if (r.code !== 0) throw new Error(`Could not create scheduled task: ${r.out.trim()}`);
  }
  fs.mkdirSync(path.dirname(startupShim()), { recursive: true });
  fs.copyFileSync(vbs, startupShim());
}

export async function uninstall(): Promise<void> {
  for (const t of [TASK, ...OLD_TASKS]) await schtasks(['/Delete', '/F', '/TN', t]);
  fs.rmSync(startupShim(), { force: true });
}

export async function status(): Promise<SchedulerStatus> {
  const q = await schtasks(['/Query', '/TN', TASK, '/XML']);
  const interval = q.code === 0;
  const logon = (interval && q.out.includes('<LogonTrigger>')) || fs.existsSync(startupShim());
  return { interval, logon };
}
